
name: 'facebook_ads_source'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  facebook_ads_source:
      example:
          materialized: view

vars:
  facebook_ads_source:
    account_history: "{{ source('facebook_ads','account_history') }}"
    ad_history: "{{ source('facebook_ads','ad_history') }}"
    ad_set_history: "{{ source('facebook_ads','ad_set_history') }}"
    basic_ad: "{{ source('facebook_ads','basic_ad') }}"
    campaign_history: "{{ source('facebook_ads','campaign_history') }}"
    creative_history: "{{ source('facebook_ads','creative_history') }}"
