name: 'facebook_ads_source_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_ads_source:
    account_history: "{{ ref('facebook_ads_account_history_data') }}"
    ad_history: "{{ ref('facebook_ads_ad_history_data') }}"
    ad_set_history: "{{ ref('facebook_ads_ad_set_history_data') }}"
    basic_ad: "{{ ref('facebook_ads_basic_ad_data') }}"
    campaign_history: "{{ ref('facebook_ads_campaign_history_data') }}"
    creative_history: "{{ ref('facebook_ads_creative_history_data') }}"

seeds:
  facebook_ads_source_integration_tests:
    facebook_ads_creative_history_data:
      +column_types:
        page_link: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        template_page_link: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"